//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAereo.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Endereco", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Endereco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_RuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_ReferenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string C_Estado {
            get {
                return this.C_EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_EstadoField, value) != true)) {
                    this.C_EstadoField = value;
                    this.RaisePropertyChanged("C_Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string C_Cidade {
            get {
                return this.C_CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.C_CidadeField, value) != true)) {
                    this.C_CidadeField = value;
                    this.RaisePropertyChanged("C_Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string C_Bairro {
            get {
                return this.C_BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.C_BairroField, value) != true)) {
                    this.C_BairroField = value;
                    this.RaisePropertyChanged("C_Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string C_Rua {
            get {
                return this.C_RuaField;
            }
            set {
                if ((object.ReferenceEquals(this.C_RuaField, value) != true)) {
                    this.C_RuaField = value;
                    this.RaisePropertyChanged("C_Rua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string C_Numero {
            get {
                return this.C_NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.C_NumeroField, value) != true)) {
                    this.C_NumeroField = value;
                    this.RaisePropertyChanged("C_Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string C_Referencia {
            get {
                return this.C_ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.C_ReferenciaField, value) != true)) {
                    this.C_ReferenciaField = value;
                    this.RaisePropertyChanged("C_Referencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_CnpjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewAereo.ServiceReference.Endereco enderecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string C_Nome {
            get {
                return this.C_NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.C_NomeField, value) != true)) {
                    this.C_NomeField = value;
                    this.RaisePropertyChanged("C_Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string C_Cnpj {
            get {
                return this.C_CnpjField;
            }
            set {
                if ((object.ReferenceEquals(this.C_CnpjField, value) != true)) {
                    this.C_CnpjField = value;
                    this.RaisePropertyChanged("C_Cnpj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public NewAereo.ServiceReference.Endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_IdentidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_IdentificacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_ContatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewAereo.ServiceReference.Endereco enderecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string C_Nome {
            get {
                return this.C_NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.C_NomeField, value) != true)) {
                    this.C_NomeField = value;
                    this.RaisePropertyChanged("C_Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string C_Identidade {
            get {
                return this.C_IdentidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.C_IdentidadeField, value) != true)) {
                    this.C_IdentidadeField = value;
                    this.RaisePropertyChanged("C_Identidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string C_Cpf {
            get {
                return this.C_CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.C_CpfField, value) != true)) {
                    this.C_CpfField = value;
                    this.RaisePropertyChanged("C_Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string C_Identificacao {
            get {
                return this.C_IdentificacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_IdentificacaoField, value) != true)) {
                    this.C_IdentificacaoField = value;
                    this.RaisePropertyChanged("C_Identificacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string C_Contato {
            get {
                return this.C_ContatoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_ContatoField, value) != true)) {
                    this.C_ContatoField = value;
                    this.RaisePropertyChanged("C_Contato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string C_Email {
            get {
                return this.C_EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.C_EmailField, value) != true)) {
                    this.C_EmailField = value;
                    this.RaisePropertyChanged("C_Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public NewAereo.ServiceReference.Endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Passagem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Passagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_PoltronaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_NumeracaoField;
        
        private System.Nullable<byte> B_CancelarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewAereo.ServiceReference.Cliente clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewAereo.ServiceReference.Empresa empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewAereo.ServiceReference.Endereco enderecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string C_Poltrona {
            get {
                return this.C_PoltronaField;
            }
            set {
                if ((object.ReferenceEquals(this.C_PoltronaField, value) != true)) {
                    this.C_PoltronaField = value;
                    this.RaisePropertyChanged("C_Poltrona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string C_Numeracao {
            get {
                return this.C_NumeracaoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_NumeracaoField, value) != true)) {
                    this.C_NumeracaoField = value;
                    this.RaisePropertyChanged("C_Numeracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<byte> B_Cancelar {
            get {
                return this.B_CancelarField;
            }
            set {
                if ((this.B_CancelarField.Equals(value) != true)) {
                    this.B_CancelarField = value;
                    this.RaisePropertyChanged("B_Cancelar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public NewAereo.ServiceReference.Cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.clienteField, value) != true)) {
                    this.clienteField = value;
                    this.RaisePropertyChanged("cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public NewAereo.ServiceReference.Empresa empresa {
            get {
                return this.empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.empresaField, value) != true)) {
                    this.empresaField = value;
                    this.RaisePropertyChanged("empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public NewAereo.ServiceReference.Endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento endereco no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirEndereco", ReplyAction="*")]
        NewAereo.ServiceReference.InserirEnderecoResponse InserirEndereco(NewAereo.ServiceReference.InserirEnderecoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirEndereco", ReplyAction="*")]
        System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirEnderecoResponse> InserirEnderecoAsync(NewAereo.ServiceReference.InserirEnderecoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento empresa no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirEmpresa", ReplyAction="*")]
        NewAereo.ServiceReference.InserirEmpresaResponse InserirEmpresa(NewAereo.ServiceReference.InserirEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirEmpresa", ReplyAction="*")]
        System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirEmpresaResponse> InserirEmpresaAsync(NewAereo.ServiceReference.InserirEmpresaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cliente no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirCliente", ReplyAction="*")]
        NewAereo.ServiceReference.InserirClienteResponse InserirCliente(NewAereo.ServiceReference.InserirClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirClienteResponse> InserirClienteAsync(NewAereo.ServiceReference.InserirClienteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento passagem no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirPassagem", ReplyAction="*")]
        NewAereo.ServiceReference.InserirPassagemResponse InserirPassagem(NewAereo.ServiceReference.InserirPassagemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirPassagem", ReplyAction="*")]
        System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirPassagemResponse> InserirPassagemAsync(NewAereo.ServiceReference.InserirPassagemRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento Cpf no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PassagemDoCliente", ReplyAction="*")]
        NewAereo.ServiceReference.PassagemDoClienteResponse PassagemDoCliente(NewAereo.ServiceReference.PassagemDoClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PassagemDoCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<NewAereo.ServiceReference.PassagemDoClienteResponse> PassagemDoClienteAsync(NewAereo.ServiceReference.PassagemDoClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirEnderecoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirEndereco", Namespace="http://tempuri.org/", Order=0)]
        public NewAereo.ServiceReference.InserirEnderecoRequestBody Body;
        
        public InserirEnderecoRequest() {
        }
        
        public InserirEnderecoRequest(NewAereo.ServiceReference.InserirEnderecoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirEnderecoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewAereo.ServiceReference.Endereco endereco;
        
        public InserirEnderecoRequestBody() {
        }
        
        public InserirEnderecoRequestBody(NewAereo.ServiceReference.Endereco endereco) {
            this.endereco = endereco;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirEnderecoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirEnderecoResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewAereo.ServiceReference.InserirEnderecoResponseBody Body;
        
        public InserirEnderecoResponse() {
        }
        
        public InserirEnderecoResponse(NewAereo.ServiceReference.InserirEnderecoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirEnderecoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InserirEnderecoResult;
        
        public InserirEnderecoResponseBody() {
        }
        
        public InserirEnderecoResponseBody(int InserirEnderecoResult) {
            this.InserirEnderecoResult = InserirEnderecoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirEmpresa", Namespace="http://tempuri.org/", Order=0)]
        public NewAereo.ServiceReference.InserirEmpresaRequestBody Body;
        
        public InserirEmpresaRequest() {
        }
        
        public InserirEmpresaRequest(NewAereo.ServiceReference.InserirEmpresaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirEmpresaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewAereo.ServiceReference.Empresa empresa;
        
        public InserirEmpresaRequestBody() {
        }
        
        public InserirEmpresaRequestBody(NewAereo.ServiceReference.Empresa empresa) {
            this.empresa = empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirEmpresaResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewAereo.ServiceReference.InserirEmpresaResponseBody Body;
        
        public InserirEmpresaResponse() {
        }
        
        public InserirEmpresaResponse(NewAereo.ServiceReference.InserirEmpresaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirEmpresaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InserirEmpresaResult;
        
        public InserirEmpresaResponseBody() {
        }
        
        public InserirEmpresaResponseBody(bool InserirEmpresaResult) {
            this.InserirEmpresaResult = InserirEmpresaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirCliente", Namespace="http://tempuri.org/", Order=0)]
        public NewAereo.ServiceReference.InserirClienteRequestBody Body;
        
        public InserirClienteRequest() {
        }
        
        public InserirClienteRequest(NewAereo.ServiceReference.InserirClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewAereo.ServiceReference.Cliente cliente;
        
        public InserirClienteRequestBody() {
        }
        
        public InserirClienteRequestBody(NewAereo.ServiceReference.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewAereo.ServiceReference.InserirClienteResponseBody Body;
        
        public InserirClienteResponse() {
        }
        
        public InserirClienteResponse(NewAereo.ServiceReference.InserirClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InserirClienteResult;
        
        public InserirClienteResponseBody() {
        }
        
        public InserirClienteResponseBody(bool InserirClienteResult) {
            this.InserirClienteResult = InserirClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirPassagemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirPassagem", Namespace="http://tempuri.org/", Order=0)]
        public NewAereo.ServiceReference.InserirPassagemRequestBody Body;
        
        public InserirPassagemRequest() {
        }
        
        public InserirPassagemRequest(NewAereo.ServiceReference.InserirPassagemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirPassagemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewAereo.ServiceReference.Passagem passagem;
        
        public InserirPassagemRequestBody() {
        }
        
        public InserirPassagemRequestBody(NewAereo.ServiceReference.Passagem passagem) {
            this.passagem = passagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirPassagemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirPassagemResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewAereo.ServiceReference.InserirPassagemResponseBody Body;
        
        public InserirPassagemResponse() {
        }
        
        public InserirPassagemResponse(NewAereo.ServiceReference.InserirPassagemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirPassagemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InserirPassagemResult;
        
        public InserirPassagemResponseBody() {
        }
        
        public InserirPassagemResponseBody(bool InserirPassagemResult) {
            this.InserirPassagemResult = InserirPassagemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PassagemDoClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PassagemDoCliente", Namespace="http://tempuri.org/", Order=0)]
        public NewAereo.ServiceReference.PassagemDoClienteRequestBody Body;
        
        public PassagemDoClienteRequest() {
        }
        
        public PassagemDoClienteRequest(NewAereo.ServiceReference.PassagemDoClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PassagemDoClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cpf;
        
        public PassagemDoClienteRequestBody() {
        }
        
        public PassagemDoClienteRequestBody(string Cpf) {
            this.Cpf = Cpf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PassagemDoClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PassagemDoClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewAereo.ServiceReference.PassagemDoClienteResponseBody Body;
        
        public PassagemDoClienteResponse() {
        }
        
        public PassagemDoClienteResponse(NewAereo.ServiceReference.PassagemDoClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PassagemDoClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewAereo.ServiceReference.Passagem PassagemDoClienteResult;
        
        public PassagemDoClienteResponseBody() {
        }
        
        public PassagemDoClienteResponseBody(NewAereo.ServiceReference.Passagem PassagemDoClienteResult) {
            this.PassagemDoClienteResult = PassagemDoClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : NewAereo.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<NewAereo.ServiceReference.WebServiceSoap>, NewAereo.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewAereo.ServiceReference.InserirEnderecoResponse NewAereo.ServiceReference.WebServiceSoap.InserirEndereco(NewAereo.ServiceReference.InserirEnderecoRequest request) {
            return base.Channel.InserirEndereco(request);
        }
        
        public int InserirEndereco(NewAereo.ServiceReference.Endereco endereco) {
            NewAereo.ServiceReference.InserirEnderecoRequest inValue = new NewAereo.ServiceReference.InserirEnderecoRequest();
            inValue.Body = new NewAereo.ServiceReference.InserirEnderecoRequestBody();
            inValue.Body.endereco = endereco;
            NewAereo.ServiceReference.InserirEnderecoResponse retVal = ((NewAereo.ServiceReference.WebServiceSoap)(this)).InserirEndereco(inValue);
            return retVal.Body.InserirEnderecoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirEnderecoResponse> NewAereo.ServiceReference.WebServiceSoap.InserirEnderecoAsync(NewAereo.ServiceReference.InserirEnderecoRequest request) {
            return base.Channel.InserirEnderecoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirEnderecoResponse> InserirEnderecoAsync(NewAereo.ServiceReference.Endereco endereco) {
            NewAereo.ServiceReference.InserirEnderecoRequest inValue = new NewAereo.ServiceReference.InserirEnderecoRequest();
            inValue.Body = new NewAereo.ServiceReference.InserirEnderecoRequestBody();
            inValue.Body.endereco = endereco;
            return ((NewAereo.ServiceReference.WebServiceSoap)(this)).InserirEnderecoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewAereo.ServiceReference.InserirEmpresaResponse NewAereo.ServiceReference.WebServiceSoap.InserirEmpresa(NewAereo.ServiceReference.InserirEmpresaRequest request) {
            return base.Channel.InserirEmpresa(request);
        }
        
        public bool InserirEmpresa(NewAereo.ServiceReference.Empresa empresa) {
            NewAereo.ServiceReference.InserirEmpresaRequest inValue = new NewAereo.ServiceReference.InserirEmpresaRequest();
            inValue.Body = new NewAereo.ServiceReference.InserirEmpresaRequestBody();
            inValue.Body.empresa = empresa;
            NewAereo.ServiceReference.InserirEmpresaResponse retVal = ((NewAereo.ServiceReference.WebServiceSoap)(this)).InserirEmpresa(inValue);
            return retVal.Body.InserirEmpresaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirEmpresaResponse> NewAereo.ServiceReference.WebServiceSoap.InserirEmpresaAsync(NewAereo.ServiceReference.InserirEmpresaRequest request) {
            return base.Channel.InserirEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirEmpresaResponse> InserirEmpresaAsync(NewAereo.ServiceReference.Empresa empresa) {
            NewAereo.ServiceReference.InserirEmpresaRequest inValue = new NewAereo.ServiceReference.InserirEmpresaRequest();
            inValue.Body = new NewAereo.ServiceReference.InserirEmpresaRequestBody();
            inValue.Body.empresa = empresa;
            return ((NewAereo.ServiceReference.WebServiceSoap)(this)).InserirEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewAereo.ServiceReference.InserirClienteResponse NewAereo.ServiceReference.WebServiceSoap.InserirCliente(NewAereo.ServiceReference.InserirClienteRequest request) {
            return base.Channel.InserirCliente(request);
        }
        
        public bool InserirCliente(NewAereo.ServiceReference.Cliente cliente) {
            NewAereo.ServiceReference.InserirClienteRequest inValue = new NewAereo.ServiceReference.InserirClienteRequest();
            inValue.Body = new NewAereo.ServiceReference.InserirClienteRequestBody();
            inValue.Body.cliente = cliente;
            NewAereo.ServiceReference.InserirClienteResponse retVal = ((NewAereo.ServiceReference.WebServiceSoap)(this)).InserirCliente(inValue);
            return retVal.Body.InserirClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirClienteResponse> NewAereo.ServiceReference.WebServiceSoap.InserirClienteAsync(NewAereo.ServiceReference.InserirClienteRequest request) {
            return base.Channel.InserirClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirClienteResponse> InserirClienteAsync(NewAereo.ServiceReference.Cliente cliente) {
            NewAereo.ServiceReference.InserirClienteRequest inValue = new NewAereo.ServiceReference.InserirClienteRequest();
            inValue.Body = new NewAereo.ServiceReference.InserirClienteRequestBody();
            inValue.Body.cliente = cliente;
            return ((NewAereo.ServiceReference.WebServiceSoap)(this)).InserirClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewAereo.ServiceReference.InserirPassagemResponse NewAereo.ServiceReference.WebServiceSoap.InserirPassagem(NewAereo.ServiceReference.InserirPassagemRequest request) {
            return base.Channel.InserirPassagem(request);
        }
        
        public bool InserirPassagem(NewAereo.ServiceReference.Passagem passagem) {
            NewAereo.ServiceReference.InserirPassagemRequest inValue = new NewAereo.ServiceReference.InserirPassagemRequest();
            inValue.Body = new NewAereo.ServiceReference.InserirPassagemRequestBody();
            inValue.Body.passagem = passagem;
            NewAereo.ServiceReference.InserirPassagemResponse retVal = ((NewAereo.ServiceReference.WebServiceSoap)(this)).InserirPassagem(inValue);
            return retVal.Body.InserirPassagemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirPassagemResponse> NewAereo.ServiceReference.WebServiceSoap.InserirPassagemAsync(NewAereo.ServiceReference.InserirPassagemRequest request) {
            return base.Channel.InserirPassagemAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewAereo.ServiceReference.InserirPassagemResponse> InserirPassagemAsync(NewAereo.ServiceReference.Passagem passagem) {
            NewAereo.ServiceReference.InserirPassagemRequest inValue = new NewAereo.ServiceReference.InserirPassagemRequest();
            inValue.Body = new NewAereo.ServiceReference.InserirPassagemRequestBody();
            inValue.Body.passagem = passagem;
            return ((NewAereo.ServiceReference.WebServiceSoap)(this)).InserirPassagemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewAereo.ServiceReference.PassagemDoClienteResponse NewAereo.ServiceReference.WebServiceSoap.PassagemDoCliente(NewAereo.ServiceReference.PassagemDoClienteRequest request) {
            return base.Channel.PassagemDoCliente(request);
        }
        
        public NewAereo.ServiceReference.Passagem PassagemDoCliente(string Cpf) {
            NewAereo.ServiceReference.PassagemDoClienteRequest inValue = new NewAereo.ServiceReference.PassagemDoClienteRequest();
            inValue.Body = new NewAereo.ServiceReference.PassagemDoClienteRequestBody();
            inValue.Body.Cpf = Cpf;
            NewAereo.ServiceReference.PassagemDoClienteResponse retVal = ((NewAereo.ServiceReference.WebServiceSoap)(this)).PassagemDoCliente(inValue);
            return retVal.Body.PassagemDoClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewAereo.ServiceReference.PassagemDoClienteResponse> NewAereo.ServiceReference.WebServiceSoap.PassagemDoClienteAsync(NewAereo.ServiceReference.PassagemDoClienteRequest request) {
            return base.Channel.PassagemDoClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewAereo.ServiceReference.PassagemDoClienteResponse> PassagemDoClienteAsync(string Cpf) {
            NewAereo.ServiceReference.PassagemDoClienteRequest inValue = new NewAereo.ServiceReference.PassagemDoClienteRequest();
            inValue.Body = new NewAereo.ServiceReference.PassagemDoClienteRequestBody();
            inValue.Body.Cpf = Cpf;
            return ((NewAereo.ServiceReference.WebServiceSoap)(this)).PassagemDoClienteAsync(inValue);
        }
    }
}
