//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCisa.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadeLojaCisa : DbContext
    {
        public EntidadeLojaCisa()
            : base("name=EntidadeLojaCisa")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LCcomprovante> LCcomprovante { get; set; }
        public DbSet<LCdepartamento> LCdepartamento { get; set; }
        public DbSet<LCdevolucao> LCdevolucao { get; set; }
        public DbSet<LCendereco> LCendereco { get; set; }
        public DbSet<LCestoque> LCestoque { get; set; }
        public DbSet<LCfincanceiro> LCfincanceiro { get; set; }
        public DbSet<LCfornecedor> LCfornecedor { get; set; }
        public DbSet<LCfuncionario> LCfuncionario { get; set; }
        public DbSet<LCproduto> LCproduto { get; set; }
        public DbSet<LCsistema> LCsistema { get; set; }
        public DbSet<LCvenda> LCvenda { get; set; }
        public DbSet<LCvendedor> LCvendedor { get; set; }
        public DbSet<LCcliente> LCcliente { get; set; }
    }
}
