//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCisa.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCendereco
    {
        public LCendereco()
        {
            this.LCfuncionario = new HashSet<LCfuncionario>();
        }
    
        public short id { get; set; }
        public string C_Endereco { get; set; }
        public string C_Numero { get; set; }
        public string C_Bairro { get; set; }
        public string C_Cidade { get; set; }
        public string C_Estado { get; set; }
        public string C_Cep { get; set; }
    
        public virtual ICollection<LCfuncionario> LCfuncionario { get; set; }
    }
}
