//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCisa.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCestoque
    {
        public short id { get; set; }
        public short LCproduto_id { get; set; }
    
        public virtual LCproduto LCproduto { get; set; }
    }
}
