//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCisa.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCfornecedor
    {
        public LCfornecedor()
        {
            this.LCproduto = new HashSet<LCproduto>();
        }
    
        public short id { get; set; }
        public string C_Marca { get; set; }
        public short LCfuncionario_id { get; set; }
    
        public virtual LCfuncionario LCfuncionario { get; set; }
        public virtual ICollection<LCproduto> LCproduto { get; set; }
    }
}
