//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCisa.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCfuncionario
    {
        public LCfuncionario()
        {
            this.C_Cnpj = "\"NULL\"";
            this.C_Telefone = "\"NULL\"";
            this.C_Celular = "\"NULL\"";
            this.C_Email = "\"NULL\"";
            this.LCfornecedor = new HashSet<LCfornecedor>();
            this.LCvendedor = new HashSet<LCvendedor>();
        }
    
        public short id { get; set; }
        public string C_Nome { get; set; }
        public string C_Cpf { get; set; }
        public string C_Cnpj { get; set; }
        public string C_Sexo { get; set; }
        public System.DateTime D_DataNasc { get; set; }
        public string C_Telefone { get; set; }
        public string C_Celular { get; set; }
        public string C_Email { get; set; }
        public short LCendereco_id { get; set; }
        public short LCdepartamento_id { get; set; }
        public short LCsistema_id { get; set; }
    
        public virtual LCdepartamento LCdepartamento { get; set; }
        public virtual LCendereco LCendereco { get; set; }
        public virtual ICollection<LCfornecedor> LCfornecedor { get; set; }
        public virtual LCsistema LCsistema { get; set; }
        public virtual ICollection<LCvendedor> LCvendedor { get; set; }
    }
}
