//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCisa.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCproduto
    {
        public LCproduto()
        {
            this.LCestoque = new HashSet<LCestoque>();
            this.LCvenda = new HashSet<LCvenda>();
        }
    
        public short id { get; set; }
        public int I_CodBarra { get; set; }
        public string C_Descricao { get; set; }
        public string C_Tamanho { get; set; }
        public string C_Cor { get; set; }
        public int I_Quantidade { get; set; }
        public double I_Valor { get; set; }
        public short LCfornecedor_id { get; set; }
    
        public virtual ICollection<LCestoque> LCestoque { get; set; }
        public virtual LCfornecedor LCfornecedor { get; set; }
        public virtual ICollection<LCvenda> LCvenda { get; set; }
    }
}
