//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCisa.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCvenda
    {
        public LCvenda()
        {
            this.LCcomprovante = new HashSet<LCcomprovante>();
            this.LCdevolucao = new HashSet<LCdevolucao>();
        }
    
        public short id { get; set; }
        public System.DateTime D_datVenda { get; set; }
        public int Quantidade { get; set; }
        public short LCproduto_id { get; set; }
        public short LCcliente_id { get; set; }
        public short LCvendedor_id { get; set; }
    
        public virtual ICollection<LCcomprovante> LCcomprovante { get; set; }
        public virtual ICollection<LCdevolucao> LCdevolucao { get; set; }
        public virtual LCproduto LCproduto { get; set; }
        public virtual LCvendedor LCvendedor { get; set; }
        public virtual LCcliente LCcliente { get; set; }
    }
}
