//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCisa.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCvendedor
    {
        public LCvendedor()
        {
            this.I_Comissao = 0D;
            this.LCdevolucao = new HashSet<LCdevolucao>();
            this.LCvenda = new HashSet<LCvenda>();
        }
    
        public short id { get; set; }
        public double I_Bonificacao { get; set; }
        public Nullable<double> I_Comissao { get; set; }
        public short LCfuncionario_id { get; set; }
    
        public virtual ICollection<LCdevolucao> LCdevolucao { get; set; }
        public virtual LCfuncionario LCfuncionario { get; set; }
        public virtual ICollection<LCvenda> LCvenda { get; set; }
    }
}
