//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceSETE.BdSete
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ST_Cliente()
        {
            this.ST_Passagem = new HashSet<ST_Passagem>();
        }
    
        public int id { get; set; }
        public string C_Nome { get; set; }
        public string C_Identidade { get; set; }
        public string C_Cpf { get; set; }
        public string C_Identificacao { get; set; }
        public string C_Contato { get; set; }
        public string C_Email { get; set; }
        public int fk_id_Endereco { get; set; }
    
        public virtual ST_Endereco ST_Endereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_Passagem> ST_Passagem { get; set; }
    }
}
