//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceSETE.BdSete
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Endereco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ST_Endereco()
        {
            this.ST_Cliente = new HashSet<ST_Cliente>();
            this.ST_Empresa = new HashSet<ST_Empresa>();
            this.ST_Passagem = new HashSet<ST_Passagem>();
        }
    
        public int id { get; set; }
        public string C_Estado { get; set; }
        public string C_Cidade { get; set; }
        public string C_Bairro { get; set; }
        public string C_Rua { get; set; }
        public string C_Numero { get; set; }
        public string C_Referencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_Cliente> ST_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_Empresa> ST_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_Passagem> ST_Passagem { get; set; }
    }
}
